### ISSUE TITLE
graph_info crah

### ISSUE THREAD

**Issue by drakkan** [Neargye/hello_tf_c_api#11]
Hi,

graph_info crashs this way:

```
21: Preprocessor/map/TensorArray_1 type: TensorArrayV3 device:  number inputs: 1 number outputs: 2
Number inputs: 1
0 type : TF_INT32
Number outputs: 2
0 type : TF_RESOURCE dims: 1 [2]
1 type : TF_FLOAT dims: 0 []

22: Preprocessor/map/while/Enter type: Enter device:  number inputs: 1 number outputs: 1
Number inputs: 1
0 type : TF_INT32
Number outputs: 1
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Annullato (core dump creato)
```

with the model here:

https://github.com/yeephycho/tensorflow-face-detection/tree/master/model

here is the backtrace:

```
#0  0x00007ffff0f79d7f in raise () from /usr/lib/libc.so.6
#1  0x00007ffff0f64672 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff132e58e in __gnu_cxx::__verbose_terminate_handler ()
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff1334dfa in __cxxabiv1::__terminate (handler=<optimized out>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff1334e57 in std::terminate () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff13350ac in __cxxabiv1::__cxa_throw (obj=<optimized out>, 
    tinfo=0x7ffff1425d10 <typeinfo for std::bad_alloc>, dest=0x7ffff13331e0 <std::bad_alloc::~bad_alloc()>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007ffff135e748 in std::__throw_bad_alloc ()
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/exception.h:63
#7  0x0000555555559836 in __gnu_cxx::new_allocator<long>::allocate(unsigned long, void const*) ()
#8  0x0000555555559719 in std::allocator_traits<std::allocator<long> >::allocate(std::allocator<long>&, unsigned long)
    ()
#9  0x000055555555953a in std::_Vector_base<long, std::allocator<long> >::_M_allocate(unsigned long) ()
#10 0x00005555555593dd in std::_Vector_base<long, std::allocator<long> >::_M_create_storage(unsigned long) ()
#11 0x000055555555921f in std::_Vector_base<long, std::allocator<long> >::_Vector_base(unsigned long, std::allocator<long> const&) ()
#12 0x000055555555907a in std::vector<long, std::allocator<long> >::vector(unsigned long, std::allocator<long> const&)
    ()
#13 0x0000555555558987 in PrintOpOutputs(TF_Graph*, TF_Operation*) ()
#14 0x0000555555558cfb in PrintOp(TF_Graph*) ()
#15 0x0000555555558d87 in main ()
```

I would like to run a session with this model, input tensor name is ``image_tensor``, and these are the output tensors

```
detection_boxes
detection_scores
detection_classes
num_detections
```

do you have any suggestions? thanks

**Comment by Neargye** [comment]
I will check it.

**Comment by Neargye** [comment]
Hi @drakkan, fix this in new master commits
